### ISSUE TITLE
یک پیشنهاد برای روند study-group

### ISSUE THREAD

**Issue by MSadeghzadehG** [ce-study-group/study-bitcoin#1]
این فاز که یه دیسکورد/اسلک ای بذارید برای هر ریپو و با یه بازه زمانی معقول (مثلا دو هفته یبار) توی یه میتینگ مجازی ای هر کسی بیاد سوالاتشو بپرسه یا یه ارائه ای بده از کلیت چیزی که فهمیده(با فاز اینکه من اینارو فهمیدم بقیه هم نظر بدن نه اینکه من بلدم بیاین گوش کنین:)) ) میتونه خیلی زیبا و اثربخش‌تر بکنه این حرکتارو

ثانیا شاید یکی دیگه هم به سرش زد که درباره این فازا بیشتر بخونه و یه جلسه بیاد ببینه فازو داره یا نه 

و کلا یه کامیونیتی ریزی شاید بتونه شکل بده و این فرهنگ یادگیری رو مخصوصا الان که دانشگاه حضوری نیست بتونه به طرز زیبایی حفظ کنه بین بچه‌ها

همینطوری در لحظه به ذهنم رسید و شایدم خودتون اصن فازو داشته باشید ولی خب دیدم گفتم به اشتراک بذارم. 
دمتون هم گرم

**Comment by smf8** [comment]
سلام. مرسی بابت پیشنهاد ها. 
الان هم روند کار ما اینجوری هست که هفته ای جلسه برگزار میکنیم و یه خلاصه ای از چیزایی که توی این هفته خوندیم رو ارائه میکنیم توی جلسه هفته بعدی. علاوه بر اون کسایی هم که مطالب جذاب و خوب دیگه ای در این موضوع پیدا کردن میان و لینک میدن یا اینکه یکوچولو خودشون توضیح میدن که بقیه هم آشنا بشن.

کامیونیتی فعلیمون توی تلگرامه ولی به نظرم اگه بتونیم یه سرور دیسکورد آماده بکنیم برای این حرکت مناسب تر باشه. @Mahanmmi
شما میتونی کمکی بفرمایی در این مورد ؟

**Comment by Mahanmmi** [comment]
یک سرور دیسکوردی زدیم امیدواریم باعث بشه مشارکت بیشتر شه :)
